public class TaskFourFunction{
//    public static void main(String[] args){
        public static int addtion(int number1, int number2){
            return number1 + number2;
}
}

        public static int even number(int number){
            if number % 2 == 0;
                return number;       
}

        public static int square(int number){
                return number*number;
}

        public static int calculate(double fahrenheit){
                fahrenheit=(int celcius*9/5)+32));
                return fahrenheit;
} 

public static int prime(int number){
                if number % 2 !== 0;
                return number;
} 

public static int area of a rectangle (int length,int width){
                
                return length * width;
} 
